export const TEXTS = {
  ru: {
   plusT: 'плюс 1',
   minusT: 'минус 1',
   deleteT: 'удалить товар',
   totalT : 'Всего:',
   pcsT: 'шт.',
   addedT: 'добавлено:',
   typeDeliveryT: 'Способ доставки',
   chooseTypeT: 'Выберите способ, как вы хотите получить товар:',
   infoAboutDeliveryT: 'Информация о доставке:',
   priceDeliveryT: 'Стоимость доставки:',
   nextBtn: 'Оформить',
   itemAdded: 'Товар добавлен',
   payBtn: 'К оплате',
   payBtn2T : 'Оплатить',
   headerT: 'Информация по доставке',
   header2T: 'Информация по оплате',
   selectCountryT: 'Выберите страну',
   addressT: 'Адресс',
   nameT: 'Имя',
   phoneT: 'Телефон',
   qtyT: 'Кол-во:',
   priceGoodT: 'Стоимость товара:',
   itogoT: 'Итого к оплате',
   successT: 'Заказ успешно оформлен!',
   infoT: 'Вы можете следить за информацией по заказу в разделе: Аккаунт > Заказы',
   myOrderT: 'Мои заказы',
   emptyCartT: 'Корзина пустая',
   toCatalogT: 'В каталог',
   enterPromocodeT: 'Укажите промокод',
   promocodePlaceholderT: 'напишите промокод',
   applyT: 'применить' 
    
  },
  en: {
    plusT: 'add 1',
   minusT: 'remove 1',
   deleteT: 'delete item',
   totalT : 'Total:',
   pcsT: 'pcs.',
   addedT: 'added:',
   typeDeliveryT: 'Delivery type',
   chooseTypeT: 'Choose the way you would like to receive items',
   infoAboutDeliveryT: 'Additional information:',
  priceDeliveryT: 'Delivery price:',
   nextBtn: 'To order',
   itemAdded: 'Item added',
   payBtn: 'To pay',
   payBtn2T : 'Pay',
   headerT: 'Delivery information',
   header2T: 'Payment information',
   selectCountryT: 'Choose country',
   addressT: 'Address',
   nameT: 'Name',
   phoneT: 'Phone',
   qtyT: 'Amount:',
   priceGoodT: 'Item price:',
   itogoT: 'Total to pay',
   successT: 'Order has been placed successfully !',
   infoT: 'You can track your order information in the section: Account > Orders',
   myOrderT: 'My orders',
   emptyCartT: 'The cart is empty',
   toCatalogT: 'To catalog',
   enterPromocodeT: 'Enter promocode',
   promocodePlaceholderT: 'fill in promocode',
   applyT: 'apply' 

   
    
  },
  de: {
    plusT: 'nachtrag 1',
   minusT: 'entfernen 1',
   deleteT: 'element löschen',
   totalT : 'Total:',
    pcsT: 'pcs.',
    addedT: 'hinzugefügt:',
     typeDeliveryT: 'Art der Lieferung',
     chooseTypeT: 'Wählen Sie, wie Sie die Sendung erhalten möchten:',
     infoAboutDeliveryT: 'Zusätzliche Informationen:',
     priceDeliveryT: 'Preis der Lieferung:',
      nextBtn: 'Arrangement',
      itemAdded: 'Artikel hinzugefügt',
    payBtn: 'Zahlbar an',
    payBtn2T : 'Bezahlen',
    headerT: 'Informationen zur Lieferung',
    header2T: 'Zahlungsinformationen',
    selectCountryT: 'Land auswählen',
    addressT: 'Adresse',
    nameT: 'Name',
    phoneT: 'Telefon',
    qtyT: 'Betrag:',
    priceGoodT: 'Artikelpreis:',
    itogoT: 'Gesamtbetrag',
    successT: 'Die Bestellung wurde erfolgreich aufgegeben!',
     infoT: 'Sie können Ihre Bestellinformationen im Bereich Konto > Bestellungen“ verfolgen',
     myOrderT: 'Meine Bestellungen',
     emptyCartT: 'Der warenkorb ist leer',
     toCatalogT: 'Katalogisieren',
     enterPromocodeT: 'Promocode eingeben',
     promocodePlaceholderT: 'promocode eingeben',
     applyT: 'anwenden' 
    
      
  },
};


  