export const TEXTS = {
  ru: {
    title: 'Настройки',
    languageT: 'Язык',
    valuteT: 'Валюта приложения',
    languageTsubtitle: 'Выберите язык',
    valuteTsubtitle: 'Выберите валюту',
    languageChangedT: 'Язык успешно изменен',
    valuteChangedT: 'Валюта приложения изменена',
    personalT:  'Личные данные',
    nameT: 'Имя',
    phoneT: 'Телефон',
    addressT: 'Адрес',
    setNameT: 'укажите имя',
    setPhoneT: 'укажите телефон',
    setAddressT: 'укажите адрес',
    aboutT: 'О магазине',
    errorT: 'Что-то пошло не так...',

    
  },
  en: {
    title: 'Settings',
    languageT: 'Language',
    valuteT: 'Base currency',
    languageTsubtitle: 'Choose language',
    valuteTsubtitle: 'Choose currency',
    languageChangedT: 'Language succesfully changed',
    valuteChangedT: 'Valute succesfully changed',
    personalT:  'Personal info',
    nameT: 'Name',
    phoneT: 'Phone',
    addressT: 'Address',
    setNameT: 'set name',
    setPhoneT: 'set phone',
    setAddressT: 'set address',
    aboutT: 'About',
    errorT: 'Something went wrong...',
   
  },
  de: {
    title: 'Einstellungen',
    languageT: 'Sprache',
    valuteT: 'Basiswährung',
    languageTsubtitle: 'Sprache wählen',
    valuteTsubtitle: 'Währung wählen',
    languageChangedT: 'Erfolgreiche Sprachänderung',
    valuteChangedT: 'Wert erfolgreich geändert',
    personalT:  'Persönliche Daten',
    nameT: 'Name',
    phoneT: 'Telefonnummer',
    addressT: 'Adresse',
    setNameT: 'Name festlegen',
    setPhoneT: 'Telefonnummer festlegen',
    setAddressT: 'Adresse festlegen',
    aboutT: 'Über',
     errorT: 'Etwas ist schiefgelaufen...',


  },
};
