export const TEXTS = {
  ru: {
   headerT: 'Мой аккаунт',
   myOrdersT: 'Мои заказы',
   settingsT: 'Настройки',
   orderFromT: 'заказ от',
   currentStatusT: 'Текущий статус заказа',
   openReceiptT: 'открыть чек',
   deliveryAddressT: 'Адресс',
   qtyT: 'Кол-во:',
   priceGoodT: 'Стоимость товара:',
   priceDeliveryT: 'Стоимость доставки:',
   itogoT: 'Итого к оплате:',
   pcsT: 'шт.',
   notPaydT: 'не оплачен',
   payBtnT: 'Оплатить',
   loadingT: 'Загрузка ...',
   myPromocodesT: 'Мои промокоды',
   saleT: 'скидка:',
   validUntilT: 'действует до:',
   notPromocodeT: 'У вас нет персональных промокодов',
   footerPromocodesT: 'Нажмите на промокод, чтобы скопировать. Примените его при оплате для получения скидки',
   copiedT: 'промокод скопирован',
   myCashbackT: 'Кэшбэк',
   myInfoT: 'Мои данные',
   purchaseQtyT: 'Всего покупок',
   purchaseSumT: 'Всего покупок на сумму',
   clientCashbackLevelT: 'Ваш уровень кешбэка',
   deltaToNextLevelT: 'Осталось до следующего уровня',
   maxLevelT: 'максимальный уровень',
   levelT: 'Уровень',
   totalSumT: 'Сумма всех сделанных покупок: от',
   fromPurchaseT: 'от покупки',
   cashbackSystemT: 'Система кешбэка',
   cashbackBallT: 'Количество баллов',
   referalSystemT: 'Реферальная система',
   refMessageT: '👆 Рекомендую данный магазин'
   
    
  },
  en: {
    headerT: 'My account',
    myOrdersT: 'My orders',
    settingsT: 'Settings',
    orderFromT: 'order from',
    currentStatusT: 'Current status of order',
    openReceiptT: 'open receipt',
    deliveryAddressT: 'Address',
    qtyT: 'Amount:',
    priceGoodT: 'Item price:',
    priceDeliveryT: 'Delivery price:',
    itogoT: 'Total to pay:',
    pcsT: 'pcs.',
    notPaydT: 'not payed',
    payBtnT: 'Pay',
    loadingT: 'Loading ...',
    myPromocodesT: 'My promocodes',
    saleT: 'sale:',
    validUntilT: 'valid until:',
    notPromocodeT: 'You have no personal promocodes now',
    footerPromocodesT: 'Click on the promo code to copy it. Apply it while pay to receive your discount.',
    copiedT: 'promocode copied',
    myCashbackT: 'Cashback',
    myInfoT: 'My information',
    purchaseQtyT: 'Purchases quantity',
    purchaseSumT: 'Purchases amount',
    clientCashbackLevelT: 'Your cachback level',
    deltaToNextLevelT: 'Purchase for the next level',
    maxLevelT: 'max level',
    levelT: 'Level',
    totalSumT: 'Total amount of all purchases made: from',
    fromPurchaseT: 'from purchase',
    cashbackSystemT: 'Cashback system',
    cashbackBallT: 'Your current cashback value',
    referalSystemT: 'Referal system',
    refMessageT: '👆 I recommend this store'
  
   
    
  },
  de: {
    headerT: 'Mein konto',
    myOrdersT: 'Meine bestellungen',
    settingsT: 'Einstellungen',
    orderFromT: 'bestellung vom',
    currentStatusT: 'Aktueller status der bestellung',
    openReceiptT: 'offene quittung',
    deliveryAddressT: 'Adresse',
    qtyT: 'Betrag:',
    priceGoodT: 'Artikelpreis:',
    priceDeliveryT: 'Preis der Lieferung:',
    itogoT: 'Gesamtbetrag:',
    pcsT: 'pcs.',
    notPaydT: 'nicht bezahlt',
    payBtnT: 'Bezahlen',
    loadingT: 'Laden ...',
    myPromocodesT: 'Meine promo-codes',
    saleT: 'sale:',
    alidUntilT: 'gültig bis:',
    notPromocodeT: 'Sie haben derzeit keine persönlichen Promo-Codes',
    footerPromocodesT: 'Klicken Sie auf den Promo-Code, um ihn zu kopieren. Geben Sie ihn beim Bezahlen ein, um den Rabatt zu erhalten',
    copiedT: 'promo-Code kopiert',
    myCashbackT: 'Cashback',
    myInfoT: 'Meine informationen',
    purchaseQtyT: 'Einkaufsmenge',
    purchaseSumT: 'Kaufsumme',
    clientCashbackLevelT: 'Ihre cashback-stufe',
    deltaToNextLevelT: 'Kauf für die nächste Stufe',
    maxLevelT: 'maximale stufe',
    levelT: 'Stufe',
    totalSumT: 'Gesamtbetrag aller getätigten einkäufe: von',
    fromPurchaseT: 'vom kauf',
    cashbackSystemT: 'Cashback-system',
    cashbackBallT: 'Ihr aktueller cashback-wert',
    referalSystemT: 'Empfehlungssystem',
    refMessageT: '👆 Ich empfehle diesen Shop weiter'
  

      
  },
};


  